=== AnnaTsukiyo/EPAM-controllers-task/input.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://com.epam.rd.java.basic.task8"
           xmlns="http://com.epam.rd.java.basic.task8">

    <xs:element name="storage">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:positiveInteger"/>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="note" type="xs:string" minOccurs="0"/>
                            <xs:element name="quantity" type="xs:positiveInteger"/>
                            <xs:element name="units" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="title" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AnnaTsukiyo/EPAM-controllers-task/input.xml
<?xml version="1.0" encoding="UTF-8"?>

<t8:storage title="kitchen"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:t8="http://com.epam.rd.java.basic.task8"
            xsi:schemaLocation="http://com.epam.rd.java.basic.task8 input.xsd">
        <!-- xsi:noNamespaceSchemaLocation="input.xsd">-->
<product>
<id>1</id>
<title>Apple</title>
<note>Green</note>
<quantity>10</quantity>
<units>kilos</units>
<price>10.90</price>
</product>

<product>
<id>2</id>
<title>Ananas</title>
<note>Hawaii</note>
<quantity>5</quantity>
<units>kilos</units>
<price>30.90</price>
</product>
        </t8:storage>

=== AnnaTsukiyo/EPAM-controllers-task/output.stax.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><t8:storage xmlns:t8="http://com.epam.rd.java.basic.task8" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" title="kitchen" xsi:schemaLocation="http://com.epam.rd.java.basic.task8 input.xsd">
        <!-- xsi:noNamespaceSchemaLocation="input.xsd">-->
<product>
<id>1</id>
<title>Apple</title>
<note>Green</note>
<quantity>10</quantity>
<units>kilos</units>
<price>10.90</price>
</product>

<product>
<id>2</id>
<title>Ananas</title>
<note>Hawaii</note>
<quantity>5</quantity>
<units>kilos</units>
<price>30.90</price>
</product>
        </t8:storage>
